name = "auto-market"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "auto-market-db"
database_id = "d648de58-32e5-43b9-bed0-7d24e981a1cd"
